In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.8.0'

In [3]:
x = [[1.]]
m = tf.matmul(x, x)
print(m)

tf.Tensor([[1.]], shape=(1, 1), dtype=float32)


In [4]:
x = tf.constant([[1, 2], [3, 4]])

In [5]:
print(x)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
x = tf.add(x, 1)
print(x)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [7]:
x.numpy()

array([[2, 3],
       [4, 5]])

In [8]:
x = tf.cast(x, tf.float32)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.]], dtype=float32)>

In [9]:
x1 = tf.ones(shape=[2, 2])
x1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
x = tf.random.normal(shape=[10])