# Series

## series的创建

In [1]:
import numpy as np
import pandas as pd

In [2]:
a = pd.Series(np.arange(10))

In [3]:
a

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [4]:
b = pd.Series([0, 1, 2, 3])
b

0    0
1    1
2    2
3    3
dtype: int64

In [5]:
color_count = pd.Series({"red":10, "green":20, "blue": 80})

In [6]:
color_count

red      10
green    20
blue     80
dtype: int64

## series的属性

In [7]:
color_count.index

Index(['red', 'green', 'blue'], dtype='object')

In [8]:
color_count.values

array([10, 20, 80], dtype=int64)

In [9]:
color_count[2]

80

# DataFrame

## DataFrame的创建

In [10]:
pd.DataFrame(np.random.randn(3, 3))

0         1         2
0  0.194596 -1.259688  0.141857
1 -0.108540  0.678668  1.130388
2 -2.652685  1.415087 -0.189759

In [11]:
score = np.random.randint(40, 100, (10, 5))

In [12]:
score

array([[74, 73, 52, 63, 83],
       [93, 46, 85, 98, 85],
       [43, 82, 92, 52, 40],
       [67, 73, 79, 76, 43],
       [40, 83, 93, 92, 98],
       [76, 55, 49, 96, 59],
       [59, 96, 60, 63, 96],
       [65, 76, 47, 89, 94],
       [57, 54, 74, 96, 79],
       [75, 99, 63, 62, 50]])

In [13]:
pd.DataFrame(score)

0   1   2   3   4
0  74  73  52  63  83
1  93  46  85  98  85
2  43  82  92  52  40
3  67  73  79  76  43
4  40  83  93  92  98
5  76  55  49  96  59
6  59  96  60  63  96
7  65  76  47  89  94
8  57  54  74  96  79
9  75  99  63  62  50

In [14]:
index = ["同学" + str(i) for i in range(score.shape[0])]

In [15]:
index

['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9']

In [16]:
cols = ["语文", "数学", "英语", "化学", "物理"]

In [17]:
score_df = pd.DataFrame(score, index=index, columns=cols)

In [18]:
score_df

语文  数学  英语  化学  物理
同学0  74  73  52  63  83
同学1  93  46  85  98  85
同学2  43  82  92  52  40
同学3  67  73  79  76  43
同学4  40  83  93  92  98
同学5  76  55  49  96  59
同学6  59  96  60  63  96
同学7  65  76  47  89  94
同学8  57  54  74  96  79
同学9  75  99  63  62  50

## DataFrame的属性

In [19]:
score_df.index

Index(['同学0', '同学1', '同学2', '同学3', '同学4', '同学5', '同学6', '同学7', '同学8', '同学9'], dtype='object')

In [20]:
score_df.columns

Index(['语文', '数学', '英语', '化学', '物理'], dtype='object')

In [21]:
score_df.values

array([[74, 73, 52, 63, 83],
       [93, 46, 85, 98, 85],
       [43, 82, 92, 52, 40],
       [67, 73, 79, 76, 43],
       [40, 83, 93, 92, 98],
       [76, 55, 49, 96, 59],
       [59, 96, 60, 63, 96],
       [65, 76, 47, 89, 94],
       [57, 54, 74, 96, 79],
       [75, 99, 63, 62, 50]])

In [22]:
score_df.shape

(10, 5)

In [23]:
score_df.head()

语文  数学  英语  化学  物理
同学0  74  73  52  63  83
同学1  93  46  85  98  85
同学2  43  82  92  52  40
同学3  67  73  79  76  43
同学4  40  83  93  92  98

In [24]:
score_df.tail()

语文  数学  英语  化学  物理
同学5  76  55  49  96  59
同学6  59  96  60  63  96
同学7  65  76  47  89  94
同学8  57  54  74  96  79
同学9  75  99  63  62  50

In [25]:
score_df.T

同学0  同学1  同学2  同学3  同学4  同学5  同学6  同学7  同学8  同学9
语文   74   93   43   67   40   76   59   65   57   75
数学   73   46   82   73   83   55   96   76   54   99
英语   52   85   92   79   93   49   60   47   74   63
化学   63   98   52   76   92   96   63   89   96   62
物理   83   85   40   43   98   59   96   94   79   50

## DataFrame索引值的设置

In [26]:
score_df

语文  数学  英语  化学  物理
同学0  74  73  52  63  83
同学1  93  46  85  98  85
同学2  43  82  92  52  40
同学3  67  73  79  76  43
同学4  40  83  93  92  98
同学5  76  55  49  96  59
同学6  59  96  60  63  96
同学7  65  76  47  89  94
同学8  57  54  74  96  79
同学9  75  99  63  62  50

In [27]:
stu = ["同学_" + str(i) for i in range(score_df.shape[0])]
stu

['同学_0',
 '同学_1',
 '同学_2',
 '同学_3',
 '同学_4',
 '同学_5',
 '同学_6',
 '同学_7',
 '同学_8',
 '同学_9']

In [28]:
score_df.shape

(10, 5)

In [29]:
score_df.index = stu

In [30]:
score_df

语文  数学  英语  化学  物理
同学_0  74  73  52  63  83
同学_1  93  46  85  98  85
同学_2  43  82  92  52  40
同学_3  67  73  79  76  43
同学_4  40  83  93  92  98
同学_5  76  55  49  96  59
同学_6  59  96  60  63  96
同学_7  65  76  47  89  94
同学_8  57  54  74  96  79
同学_9  75  99  63  62  50

In [31]:
df = score_df.reset_index()
df

index  语文  数学  英语  化学  物理
0  同学_0  74  73  52  63  83
1  同学_1  93  46  85  98  85
2  同学_2  43  82  92  52  40
3  同学_3  67  73  79  76  43
4  同学_4  40  83  93  92  98
5  同学_5  76  55  49  96  59
6  同学_6  59  96  60  63  96
7  同学_7  65  76  47  89  94
8  同学_8  57  54  74  96  79
9  同学_9  75  99  63  62  50

In [32]:
df2 = df.set_index("index")
df2

语文  数学  英语  化学  物理
index                    
同学_0   74  73  52  63  83
同学_1   93  46  85  98  85
同学_2   43  82  92  52  40
同学_3   67  73  79  76  43
同学_4   40  83  93  92  98
同学_5   76  55  49  96  59
同学_6   59  96  60  63  96
同学_7   65  76  47  89  94
同学_8   57  54  74  96  79
同学_9   75  99  63  62  50

In [33]:
df2.index.name = 'jj'

In [34]:
df2

语文  数学  英语  化学  物理
jj                      
同学_0  74  73  52  63  83
同学_1  93  46  85  98  85
同学_2  43  82  92  52  40
同学_3  67  73  79  76  43
同学_4  40  83  93  92  98
同学_5  76  55  49  96  59
同学_6  59  96  60  63  96
同学_7  65  76  47  89  94
同学_8  57  54  74  96  79
同学_9  75  99  63  62  50

## 把某一列的值设为新的索引

In [35]:
df = pd.DataFrame({"month":[2,4,5,8],
                  "year":[2021,2022,2023,2024],
                  "data":[3,13,18,23]})

In [36]:
df

month  year  data
0      2  2021     3
1      4  2022    13
2      5  2023    18
3      8  2024    23

In [37]:
df.set_index("year")

month  data
year             
2021      2     3
2022      4    13
2023      5    18
2024      8    23

In [38]:
df2 = df.set_index(["year", "month"])

In [39]:
df2

data
year month      
2021 2         3
2022 4        13
2023 5        18
2024 8        23

In [40]:
df2.index.levels

FrozenList([[2021, 2022, 2023, 2024], [2, 4, 5, 8]])